# Generated by Django 3.2.8 on 2021-10-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userMaster',
            fields=[
                ('fname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(default='', max_length=100)),
                ('cpassword', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
